### ISSUE TITLE
Why are you not commiting the Cargo.lock file?

### ISSUE THREAD

**Issue by jonasgeiler** [khvzak/lua-ryaml#1]
This is more of a question than an issue. I'm a bit new to Rust/Crates.

The Cargo Book says the following:
> If you’re building a non-end product, such as a rust library that other rust [packages](https://doc.rust-lang.org/cargo/appendix/glossary.html#package) will depend on, put `Cargo.lock` in your `.gitignore`. If you’re building an end product, which are executable like command-line tool or an application, or a system library with crate-type of `staticlib` or `cdylib`, check `Cargo.lock` into `git`.

Now, your library uses a crate-type of `cdylib` which means it's recommended to check `Cargo.lock` into git.
Is there a reason you're no including it?

I'm currently building a Lua library using your awesome `mlua` crate, and I'm wondering if I should include the `Cargo.lock` file in my LuaRocks module or not... None of the other LuaRocks modules that are using `mlua` have included it, so I'm a little thrown off.

Maybe 2 years ago, when you wrote this thing, this wasn't described yet in The Cargo Book?

**Comment by khvzak** [comment]
Seems this is by mistake!
